In [ ]:
def rotate_image(matrix):
    '''
    INPUT: Matrix: 2D matrix representing image 
    
    OUTPUT: Matrix: same 2D matrix but rotated 90 degrees clockwise. 
    
    '''
    

In [4]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
type(matrix)

list

In [10]:
matrix_rotate = []
for i in matrix:
    print(i)
    test = []
    test.append
print(test)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[7]


In [16]:
import numpy as np

matrix_2 = np.array(matrix)
matrix_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
test = matrix_2[:,0]
print(test)
#need to invert the list. 
test[::-1]
print(test)
test_1_lst = test.tolist()
test_1_lst

[1 4 7]
[1 4 7]


[1, 4, 7]

In [33]:
test_2 = matrix_2[:,1]
test_2[::-1]
test_2_lst = test_2.tolist()
test_2_lst

[2, 5, 8]

In [ ]:
test_3 = matrix_3[:,3]


In [19]:
to_list = matrix_2.tolist()
to_list
type(to_list)

list

In [2]:
test_matrix = [[1,2,3], [4,5,6], [7,8,9]]
test_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
final_matrix 
for lst in test_matrix:
    print(lst)
    final_matrix.append(lst[0])
print(final_matrix)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[1, 4, 7]
